apiVersion: v1
kind: Service
metadata:
  name: {{ include "test-app-chart.fullname" . }}
  labels:
    app: {{ include "test-app-chart.name" . }}
    {{- include "test-app-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "test-app-chart.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 8000
